# Generated by Django 4.2.5 on 2023-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='img',
            field=models.ImageField(default=0, upload_to='static/test/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
